{
    "name": "OKR Objectives and Competencies",
    "summary": "This will Manages Employee's Ratings",
    "version": "1.0",
    "license": "LGPL-3",
    "author": "Fawad",
    "category": "",
    "depends": ['mail', 'base', 'hr'],
    "data": [
        'security/ir.model.access.csv',
        'views/okr.xml',
        'views/type.xml',
        'views/objective.xml',
        'views/portal/objective.xml',
        'security/security.xml',
        'views/time.xml',
        'views/competencies.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/banner.png'],
    'price': 130,
    'currency': "USD",
}

