{
    "name": "FBR Integration Multi Company",
    "version": "20.0.0.1",
    "summary": "Send invoices to FBR (Federal Board of Revenue Pakistan)",
    "description": "Integrate Odoo invoices with FBR's real-time invoice reporting system.",
    "category": "Accounting",
    "author": "Fawad Hussain (Developer) & Umer Hayat (Functional Consultant)",
    "depends": ["base", "account", "product"],
    # the two variants patch the same invoice views: only one can be installed
    "excludes": ["fbr_integration"],
    "data": [
        "data/data.xml",
        "views/company.xml",
        "views/move.xml",
        "views/views.xml",
        "reports/invoice_report.xml",
        "views/logs_view.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    'price': 130,
    'currency': "USD",
    'images': ['static/description/banner.png'],
}
