# -*- coding: utf-8 -*-
{
    'name': 'Hospital Management System',
    'summary': 'Hospital Management System having all HMS modules',
    'description': """
        all hms modules by hms pb hms PackBytes Hospital Management System Premium. pb hms hospital management system by packbytes consulting services. hospital certificate and medical certification medical document management hospital barcode system insurance management system laboratory management system radiology and pathology management next patient screen, manage vitals signs of patient in appointment and also details of all the physical examinations of patient.
    """,
    'images': ['static/description/banner.png'],
    'version': '19.0.1.0.0',
    'category': 'Medical',
    'author': 'PackBytes',
    'support': 'sales@packbytes.com',
    'website': 'https://www.packbytes.com',
    'license': 'OPL-1',
    'depends': [
        'pb_hms_base',
        'pb_hms',
        'pb_hms_barcode',
        'pb_hms_certification',
        'pb_hms_dashboard',
        'pb_hms_hospitalization',
        'pb_document_base',
        'pb_documents_preview',
        'pb_hms_documents_preview',
        'pb_hms_insurance',
        'pb_hms_insurance_hospitalization',
        'pb_hms_insurance_laboratory',
        'pb_laboratory',
        'pb_hms_laboratory',
        'pb_hms_laboratory_hospitalization',
        'pb_hms_next_patient_screen',
        'pb_pharmacy',
        'pb_hms_pharmacy',
        'pb_hms_vaccination',
        'pb_hms_portal',
        'pb_certification',
        'pb_hms_commission',
        'pb_facility_management',
        'pb_hms_online_appointment',
        'pb_hms_operation_theater',
        'pb_hms_icd10',
        'pb_hms_webcam',
        'pb_invoice_split',
        'pb_hms_insurance_radiology',
        'pb_radiology',
        'pb_hms_radiology',
        'pb_hms_radiology_hospitalization',
        # Extra Modules
        'pb_hms_blood_bank',
        'pb_hms_medical_representative',
        'pb_sms',
        'pb_hms_sms',
        'pb_hms_subscription',
        'pb_hms_subscription_physiotherapy',
        'pb_hms_ambulance',
        'pb_video_call',
        'pb_jitsi_meet',
        'pb_hms_video_call',
        'pb_whatsapp',
        'pb_whatsapp_meta',
        'pb_hms_whatsapp',
        'pb_pharmacy_whatsapp',
        'pb_laboratory_whatsapp',
        'pb_radiology_whatsapp',
        'pb_hms_rating',
        'pb_hms_nursing',
        'pb_invoice_barcode',
        'pb_invoice_with_stock_move',
        'pb_product_barcode_generator',
        'pb_consent_form',
        'pb_hms_consent_form',
        'pb_commission',
        'pb_hms_vital_examination',
        'pb_portal_user_image',
        'pb_invoice_summary',
        'pb_hms_invoice_summary',
        'pb_web_timer_widget',
        'pb_hms_recurring_procedure',
        'pb_hms_pharmacy_pos',
        'pb_hms_survey',
        'pb_hms_insurance_surgery',
        'pb_hms_body_chart',
        # Speciality Related Modules
        'pb_hms_aesthetic',
        'pb_hms_physiotherapy',
        'pb_hms_gynec',
        'pb_hms_paediatric',
        'pb_hms_ophthalmology',
        'pb_hms_dental',
        'pb_hms_dental_chart',
        'pb_hms_emergency',
        # Branch Modules
        'pb_branch_base',
        'pb_branch_account',
        'pb_branch_stock',
        'pb_hms_branch',
        'pb_branch_laboratory',
    ],
    'data': [
    ],
    'installable': True,
    'application': True,
    'sequence': 1,
    'price': 30,
    'currency': 'USD',
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
